### PR TITLE
include version information

### LINKED ISSUE #24: Warning in Startup Logs
The following in being generated in the logs for this integration:

Logger: homeassistant.loader
Source: loader.py:802
First occurred: 5:39:20 PM (1 occurrences)
Last logged: 5:39:20 PM

No 'version' key in the manifest file for custom integration 'smartweatherudp'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'smartweatherudp'

### PR DESCRIPTION
**Pull request by leonardpitzu**
fixes #24

### CODE REVIEW

**Comment by zacs** [comment]
@briis Would you mind merging this PR since in June this will cause the component to stop loading? As always thanks again for this component!

**Comment by suiciety** [comment]
> @briis Would you mind merging this PR since in June this will cause the component to stop loading? As always thanks again for this component!

+1 this has happened now and the integration errors out.

**Comment by mrpathos** [comment]
Just came here to submit this exact change. Without this the integration no longer loads.

**Comment by christianlappin** [comment]
I have manually added the version to my manifest locally so if we can merge this branch it will fix the integration for those who don't feel comfortable editing the final manually.

**Comment by p0isson** [comment]
@LuckyJayDIY  would you mind merging this please?

**Comment by FireBall1725** [comment]
+1 to get this merged

**Comment by lkorth** [comment]
#31 is likely preferable as it also updates the release version

**Comment by natekspencer** [comment]
Closing in favor of #31

**Pull request closed without merging**
